---

- hosts: all
  become: yes
  user: vagrant
  vars:
    ansible_hostname: "hw11nginx"
    server_port: 8080
    server_name: "nginx"

  tasks:
#    - name: yum update
#      yum: name=* state=latest

    - name: Install epel
      yum: 
        name: epel-release 
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install nginx
      yum: 
        name: nginx 
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Copy index.html
      template: 
        src: /home/vagrant/index.html.j2 
        dest: /usr/share/nginx/html/index.html
      notify: Restart nginx

    - name: Copy site config
      template: 
        src: /home/vagrant/default.conf.j2 
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx
    
    - name: service nginx started
      service: 
        name: nginx
        state: started
        enabled: yes
    
    - name: enable service nginx
      systemd:
        name: nginx
        enabled: yes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes