# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']


MACHINES = {
  :'bareos-dir' => {
        :box_name => "centos/7",
        :box_version => "1811.02",
        :ip_addr => '192.168.33.12',
    :disks => {
        :sata1 => {
            :dfile => home + '/VMDisks/lvm/sata3.vdi',
            :size => 10240, # Megabytes
            :port => 1
        }
    }
  },
  :'bareos-client' => {
        :box_name => "centos/7",
        :box_version => "1811.02",
        :ip_addr => '192.168.33.13',
    :disks => {
        :sata1 => {
            :dfile => home + '/VMDisks/lvm/sata2.vdi',
            :size => 10240, # Megabytes
            :port => 1
        }
    }
  }
}
#################### Цикл с оющими настройками
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.box_version = boxconfig[:box_version]

          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
                  vb.customize ["modifyvm", :id, "--memory", "1000"]
          vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

          boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
                vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
              end
              vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

          end
          end
#################### Ветвление по именам
      case boxname.to_s
      when "bareos-dir"
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
        yum makecache
        yum install -y epel-release
        yum install -y wget
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        yum install -y sshpass
        yum install -y net-tools
      SHELL

      box.vm.provision "file", source: "my.cnf.j2", destination: "/home/vagrant/my.cnf.j2"
      box.vm.provision "file", source: "bacula-dir.conf.jinja2", destination: "/home/vagrant/bacula-dir.conf.jinja2"
      box.vm.provision "file", source: "bconsole.conf.jinja2", destination: "/home/vagrant/bconsole.conf.jinja2"
      box.vm.provision "file", source: "bacula-sd.conf.jinja2", destination: "/home/vagrant/bacula-sd.conf.jinja2"
      box.vm.provision "file", source: "bacula-fd.conf.jinja2", destination: "/home/vagrant/bacula-fd.conf.jinja2"
      box.vm.provision "file", source: "filesets.conf.jinja2", destination: "/home/vagrant/filesets.conf.jinja2"

      box.vm.provision :ansible_local do |guest_ansible|
        guest_ansible.inventory_path = "hosts"
        guest_ansible.playbook = "playbook-server.yml"
        guest_ansible.become = true
      end

      when "bareos-client"
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
        yum makecache
        yum install -y epel-release
        yum install -y wget
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        yum install -y sshpass
        yum install -y net-tools
      SHELL

      box.vm.provision "file", source: "client-bacula-fd.conf.jinja2", destination: "/home/vagrant/client-bacula-fd.conf.jinja2"
      box.vm.provision "file", source: "pools.conf.jinja2", destination: "/home/vagrant/pools.conf.jinja2"
      box.vm.provision "file", source: "dir-clients.conf.jinja2", destination: "/home/vagrant/dir-clients.conf.jinja2"
      

      box.vm.provision :ansible_local do |guest_ansible|
        guest_ansible.inventory_path = "hosts"
        guest_ansible.playbook = "playbook-agent.yml"
        guest_ansible.become = true
      end
  end
end
end
end